wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1666817147.413714
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.6
      5: 0.13.3
      8:
      - 5
batch_size:
  desc: null
  value: 64
dry_run:
  desc: null
  value: false
epochs:
  desc: null
  value: 14
gamma:
  desc: null
  value: 0.7
log_interval:
  desc: null
  value: 10
lr:
  desc: null
  value: 1.0
no_cuda:
  desc: null
  value: false
no_mps:
  desc: null
  value: false
save_model:
  desc: null
  value: false
seed:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 1000
